----
-- phpLiteAdmin database dump (http://www.phpliteadmin.org/)
-- phpLiteAdmin version: 1.9.7.1
-- Exported: 2:53pm on December 13, 2024 (UTC)
-- database file: ../db/consentsdb
----
BEGIN TRANSACTION;

----
-- Table structure for consents
----
CREATE TABLE consents (token TEXT, ctime TEXT, mail TEXT, dominio TEXT, gads TEXT, gtag TEXT, clave TEXT, analitics TEXT, analytics TEXT, color TEXT, background TEXT, link TEXT, script TEXT, position TEXT, zoom TEXT, vertical TEXT, contrast TEXT, nombre TEXT, altura TEXT, enlace TEXT, cross TEXT, hiddenid TEXT, deshabilitado TEXT, CIF TEXT, notis TEXT);
-- Añadir las nuevas columnas a la tabla consents si no existen
ALTER TABLE consents ADD COLUMN tc_string TEXT;
ALTER TABLE consents ADD COLUMN consent_data TEXT;
ALTER TABLE consents ADD COLUMN updated_at TEXT;
ALTER TABLE consents ADD COLUMN purposes TEXT;

-- Crear índice para mejorar el rendimiento
CREATE INDEX IF NOT EXISTS idx_consents_token ON consents(token);
----
-- Data dump for consents, a total of 41 rows
----
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('1','1693560222','JOANLOPEZCABRERA1988@GMAIL.COM','anonimchat.es',NULL,'GTM-5TCMXQSN','4444',NULL,'G-8ZJEXQDST3','#FF6666','#FFFFFF','','','right','0.75','bottom','#FF6666','Chat anónimo','60','https://anonimchat.es','crossid','hiddenid',NULL,'X',NULL);
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('aquitodo','1693567474','www.aquitodo.es@gmail.com','aquitodo.es',NULL,'GTM-5TCMXQSN','4444',NULL,'G-8ZJEXQDST3','','#FFFFFF','https://aquitodo.es/aquitodo.html/es/info/faq/','','','1','','','aquiTODO','90','https://aquitodo.es','','',NULL,'X','on');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('cambiazos','1693658896','cambiazosclasificados@gmail.com','cambiazos.com',NULL,'GTM-NTTCC44B','4444',NULL,'G-J2SH1S78Z3','#000000','#FFFFFF','https://cambiazos.com/politicas-p25','','left','1','bottom','#757575','Cambiazos','100','https://cambiazos.com','','','NO','X','on');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('cbb9350','1697878030','hormimpreso.barcelona@gmail.com','hormigon-impreso-barcelona.com',NULL,'GTM-TMH7WPN3','4444',NULL,'G-R36TBWJRPB','#FF0000','#FFFFFF','https://hormigon-impreso-barcelona.com/blog/informacion-legal-politica-de-privacidad-proteccion-de-datos-y-derechos-de-autor/','','left','0.75','bottom','transparent','Hormigón Impreso Barcelona','90','https://www.hormigon-impreso-barcelona.com/','crossid','hiddenid',NULL,'X',NULL);
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('hormigon-catalunya','1706405203','hormigon.catalunya.es@gmail.com','',NULL,'G-5EBMWJ02PQ','4444',NULL,'G-5EBMWJ02PQ','#000000','#FFFFFF','','','left','0.75','bottom','#fdbe33','Hormigón Catalunya ES','95','https://www.hormigon-catalunya.es','crossid','hiddenid','NO','X','');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('5de0482','1712145614','info@cookie21.com','',NULL,'','FG890@s',NULL,'','#336699','#c0c0c0','','','right','1','bottom','transparent','Nat 21','90','https://www.cookie21.com/','crossid','',NULL,'B87509160','on');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('f153365','1712147258','info@data21.es','',NULL,'','TY784#44',NULL,'','#336699','#c0c0c0','','','right','1','bottom','transparent','Data21','90','https://www.data21.es/','crossid','',NULL,'B87509160','on');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('4d33fbb','1712147540','info@miregistrolaboral.es','',NULL,'','Rtw2309',NULL,'','#336699','#c0c0c0','','','right','1','bottom','transparent','Mi Registro Laboral','90','https://www.miregistrolaboral.es/','crossid','',NULL,'B87509160','on');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('aa2e7dc','1712148193','info@sistemadeinformacion.es','',NULL,'','U189T%17',NULL,'','#336699','#c0c0c0','','','right','1','bottom','transparent','Sistema De Información','90','https://sistemadeinformacion.es/','crossid','',NULL,'B87509160','on');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('demo','1712341108','joanlcwebmaster@gmail.com','',NULL,'','4444',NULL,'','#336699','#c0c0c0','','','right','1','bottom','transparent','Cookie21','90','https://cookie21.com/cm/','','',NULL,'B87509160','on');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('8209d3a','1714985476','josuegl836@gmail.com','',NULL,'','FG56-1',NULL,'','#336699','#c0c0c0','','','right','1','bottom','transparent','Pruebas','90','https://www.cookie21.com','crossid','hiddenid',NULL,'3456789','on');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('b84f475','1718279688','soporte@tmwebs.es','',NULL,'6236139268','Tm47/webs',NULL,'74666996','#336699','#c0c0c0','','','right','1','bottom','transparent','Tmwebs Cloud Sl.','90','https://www.tmwebs.es/','crossid','',NULL,'B14968283','on');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('e59390b','1720611755','aurelio.martinez.calvo@gmail.com','',NULL,'','C78&bh30',NULL,'','#336699','#c0c0c0','','','right','0.75','bottom','transparent','YUBERO GOURMET SL','70','https://yuberogourmet.es','','',NULL,'B06853535 ','');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('5e2373e','1721028687','juandestroyer@mariskalrock.com','',NULL,'','mARISKAL2121',NULL,'','#FF0000','#FFFFFF','','','','1','','','MariskalRock','90','https://mariskalrock.com','','','NO','A79105771','on');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('b947fce','1722442639','marqueting@ohcomunicacio.cat','',NULL,'','C78&bh30',NULL,'','#336699','#c0c0c0','','','left','1','bottom','transparent','Can Garús, S.L.U..','80','https://www.cangarus.com','','',NULL,'B55222764','');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('6243b6d','1722498988','alvilamp@alvilamp.com','',NULL,'','Alvilamp21',NULL,'','#336699','#c0c0c0','','','right','1','bottom','transparent','TELMA DESIGN, S.L.','90','https://alvilamp.com','','',NULL,'B44671071','');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('8d7bd46','1722499096','alvilamp@alvilamp.com','',NULL,'','C78&bh30',NULL,'','#336699','#c0c0c0','','','right','1','bottom','transparent','TELMA DESIGN, S.L.','90','https://pruebas.alvilamp.com','','',NULL,'B44671071','');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('a4710dc','1724145542','aalamos@eccuo.com','',NULL,'','Holisi21',NULL,'','#FF66CC','#FFFFFF','','','right','1','bottom','#FF66CC','SAUCE COSMETICS, S.L.','90','https://www.holisi.es','','',NULL,'B72951536','');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('05bfc0c','1725215716','marcos@tmwebs.es','',NULL,'','C78&bh30',NULL,'','#336699','#c0c0c0','https://dentibell.es/aviso-legal/','','left','1','bottom','transparent','DENTIBELL SALUD','90','https://dentibell.es/','','',NULL,'B70814470 ','');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('8561b81','1725365624','marcos@tmwebs.es','',NULL,'','C78&bh30',NULL,'','#65AE84','#ffffff','https://iberdata21.com/aviso-legal/','','left','1','bottom','#c0c0c0','IBERDATA21','60','https://iberdata21.com/','','',NULL,'B14882617','');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('kandini','1726522727','magik_kandini@hotmail.com','',NULL,'','4444',NULL,'','#FFFFFF','#000000','https://www.magikkandini.com/cookies','','right','0.75','bottom','#FF0000','MagikKandini','95','https://www.magikkandini.com','crossid','hiddenid','SI','Privacy-Protected','');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('3988564','1726591526','teresa.aguado@tatdatos.es','',NULL,'','C78&bh30',NULL,'','#828282','#F7EEEA','https://naserpsicologia.com/aviso-legal-politica-de-privacidad/','','left','1','bottom','transparent','NaSer Psicología - Anuska Garcia Linares','40','http://www.naserpsicologia.com','','',NULL,'09042077H','');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('b6ff1ca','1726744051','direccion@aeione.es','',NULL,'','C78&bh30',NULL,'','#336699','#c0c0c0','https://aeione.es/privacidad','','right','1','bottom','transparent','GRUPO AEIONE S.L. ','90','https://aeione.es/','','',NULL,'B56731045 ','');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('carolae','1726752974','info@carolae.com','',NULL,'','4444',NULL,'','#FF00CC','#FFFFFF','','','right','0.75','bottom','transparent','Carolae','20','http://carolae.com','','hiddenid','NO','PROTECTED','');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('c21f45d','1727190980','enquisa@enquisa.com','',NULL,'','C78&bh30',NULL,'','#4089c1','#ebebeb','https://www.enquisa.com/politica-de-privacidad','','left','1','bottom','#4089c1','ENQUISA, S.L.','40','https://enquisa.com/','','',NULL,'B15370901','');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('ejemplo-pers','1727206270','','',NULL,'','',NULL,'','#336699','#c0c0c0','','https://cookie21.com/cm/gracias.js','right','1','bottom','transparent','Cookis21 (Ejemplo pers)','90','http://cookie21.com/cm','','',NULL,'PRIVATE','');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('3fe3b3e','1727968415','marqueting@ohcomunicacio.cat','',NULL,'','C78&bh30',NULL,'','#000000','#ffffff','https://www.gcserveisimmobiliaris.com/es/aviso-legal-casas-pisos-girona-barcelona','','left','1','bottom','transparent','GERARD COMAMALA PLANA (GC SERVEIS IMMOBILIARIS)','90','https://www.gcserveisimmobiliaris.com','','',NULL,'77914864H','');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('1f4a66f','1729008975','marqueting@ohcomunicacio.cat','',NULL,'','C78&bh30',NULL,'','#FF0033','#ffffff','https://www.tax.es/es/legal/politica-de-cookies','','left','1','bottom','transparent','TAX INFORMATION TECHNOLOGIES, SL','90','https://www.tax.es','','',NULL,'B17455379','');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('202674f','1729091386','albertosaez@prodanaconsultores.com','',NULL,'','C78&bh30',NULL,'','#3366FF','#3399FF','https://www.prodanaconsultores.com/aviso-legal-y-politica-de-cookies/','','right','1','bottom','transparent','Prodana Consultores S.L ','90','https://www.prodanaconsultores.com/','','',NULL,'B71380380','');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('905e3c3','1729771959','maria@ladonaira.com','',NULL,'','Donaira2121',NULL,'','#003300','#c0c0c0','https://www.ladonaira.com/privacy-policy','','right','1','bottom','transparent','FINCA LA DONAIRA, S.L.','90','https://www.ladonaira.com','','',NULL,'B92629112 ','');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('b51dd52','1730223814','ana.goni@agotzaina.com','',NULL,'','Agotzaina21',NULL,'','#990033','#CC0033','https://agotzaina.com/politica-de-privacidad/','','right','1','bottom','transparent','AGOTZAINA, S.L.','90','https://agotzaina.com/','','',NULL,'B31668932','');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('75b7596','1731233195','teresa.aguado@tatdatos.es','',NULL,'','pEREANTON21',NULL,'','#3300FF','#FFFFCC','https://www.pereanton.com/aviso-legal-y-politica-de-privacidad/','','right','1','bottom','#FFFF66','PEREANTON INDUSTRIAS DEL VIDRIO, S.L.','44','https://www.pereanton.com/','','',NULL,'B56784101','');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('2372970','1731519743','marcos@tmwebs.es','',NULL,'','tmWEBS2121',NULL,'','#33CC33','#FFFFFF','https://buktiem.com/aviso-legal-y-politica-de-privacidad/','','right','0.75','bottom','transparent','TMWEBS CLOUD, S.L.','50','https://buktiem.com/','','',NULL,'B14968283 ','');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('7f6607f','1731671114','teresa.aguado@tatdatos.es','',NULL,'','C78&bh30',NULL,'','#336699','#c0c0c0','https://tucanagestion.com/aviso.html','','right','1','bottom','transparent','PENTÁGONO UNIVERSAL S.L.','90','https://tucanagestion.com','','',NULL,'B19179639','');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('3ac692b','1731671374','a.ledezma@corquimia.com','',NULL,'','C78&bh30',NULL,'','#336699','#009999','https://factorchem.com/politica-de-privacidad/','','right','1','bottom','transparent','CORQUIMIA INDUSTRIAL, S.L.','90','https://factorchem.com','','',NULL,'B64388721','');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('f73ce7c','1732020790','info@psigma.cat','',NULL,'','C78&bh30',NULL,'','#336699','#c0c0c0','http://www.psigma.cat/avis-legal/','','right','1','bottom','#CC0099','Roger Puigdecanet Riubugent','90','https://www.psigma.cat','','',NULL,'33947179F','');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('975aac9','1732194267','joanlc1988@gmail.com','',NULL,'','4444',NULL,'','#336699','#c0c0c0','','','right','1','bottom','transparent','JoanL(C)','90','http://','','',NULL,'','');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('7e7af24','1733080650','teresa.aguado@tatdatos.es','',NULL,'','C78&bh30',NULL,'','#336699','#c0c0c0','','','right','1','bottom','transparent','IGLESIA BAUTISTA LA CRUZ','90','https://iglesiabautistalacruz.com','','',NULL,'R1900058G','');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('1cadfe7','1733738858','info@codiceasesores.com','',NULL,'','C78&bh30',NULL,'','#66CC33','#c0c0c0','https://www.codiceasesores.com/nota-legal/','','right','1','bottom','transparent','CODICE ASESORES S.L.','90','https://www.codiceasesores.com','','',NULL,'B85993830 ','');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('formigoCat','1733766118','formigo.catalunya@gmail.com','',NULL,'GTM-595JD7VJ','4444',NULL,'','#336699','#a9cce3','https://formigo-catalunya.es/blog/privacidad/','','left','1','bottom','transparent','Formigó Catalunya','90','http://www.formigo-catalunya.es','crossid','hiddenid',NULL,'www.formigo-catalunya.es','');
INSERT INTO "consents" ("token","ctime","mail","dominio","gads","gtag","clave","analitics","analytics","color","background","link","script","position","zoom","vertical","contrast","nombre","altura","enlace","cross","hiddenid","deshabilitado","CIF","notis") VALUES ('69f7d05','1733837148','marqueting@ohcomunicacio.cat','',NULL,'','C78&bh30',NULL,'','#3399CC','#c0c0c0','https://www.probrava.com/es/politica-de-privacidad','','left','1','bottom','transparent','PROYECTOS NÁUTICOS COSTA BRAVA 2014, S.L.','90','https://www.probrava.com','','',NULL,'B55217186','');
COMMIT;
